### ISSUE TITLE
Use a shared calendar for project meetings

### ISSUE THREAD

**Issue by mogul** [18F/cic-site#2]
In order to keep visibility of project activity high and involvement consistent, we want a shared calendar for the CIC project that canonically displays rituals that are on a cadence and who's expected to attend them.

ACs:
- [x] There's a shared calendar for the CIC project
- [x] "Accountable" people all have administrative access to the calendar
- [x] Sprint review, retro, and planning rituals are set up and recurring
- [ ] Appropriate mailing aliases are used for managing the set of people invited

**Comment by jenniferthibault** [comment]
I'm holding off on using mailing addresses until we know a bit more about the team (or until it grows and needs more management). It's a pretty manageable size right now. 

Otherwise, this is about halfway done, just working with Maggie to schedule the sprint review on Crystal's calendar, and after that, I'll add the retro too.

**Comment by jenniferthibault** [comment]
Scheduled ALL THE THINGS! Closing
